### ISSUE TITLE
Can't display string

### ISSUE THREAD

**Issue by incues** [Tinkertanker/pxt-oled-ssd1306#10]
When using the new version of the PXT editor (makecode), I am unable to display a string. Instead of a string, a random symbol is shown on the display. Numbers are still working fine.

Wondering if that could be a buffer or simply a character set issue with the new editor.
Has anyone tested it yet and can confirm the issue?

**Comment by nioq** [comment]
Thanks for filing! Fixed in 7d9acfdc6ce13d62cb90bd88027d6b95dac0a77d, available in v1.2.4
