### ISSUE TITLE
Issue when using  32 x 128 displays

### ISSUE THREAD

**Issue by microbit-mark** [Tinkertanker/pxt-oled-ssd1306#14]
microbit support: 19778

When using a smaller, 32x128 OLED with this package, it does not update with every new line.
Initially the first line is displayed then it only updates every second time.
Also same result with 'show string "..."'
Works as expected on larger 64x128 OLED

![oled code example](https://user-images.githubusercontent.com/31242877/50891350-f92d7f80-13f3-11e9-8f88-fec628b6f0cb.JPG)

**Comment by firemansamm** [comment]
Hi Mark!

That's odd - thanks for raising, I'll investigate this. Haven't got a 128x32 OLED on hand although I've ordered one, it'll take a bit of time for it to get here before I can replicate.  I should have some additional information by this weekend, hopefully.

**Comment by firemansamm** [comment]
Should be fixed in v1.2.6, pending testing.

**Comment by firemansamm** [comment]
Tested and verified fixed on hardware. @microbit-mark, please do let us know if the issue resurfaces. Closing.
