### ISSUE TITLE
Can't complie after adding the extension

### ISSUE THREAD

**Issue by DoraLC** [Tinkertanker/pxt-oled-ssd1306#18]
As mentioned in the title, compilation fails after adding the extension. 

makecode.microbit.org version:  2.0.3

Microsoft MakeCode version:  5.15.10

microbit runtime version:  pxtgc-0

**Comment by yjsoon** [comment]
Fixed in https://github.com/Tinkertanker/pxt-oled-ssd1306/commit/6175b56c276d116eb5dae9b6d298093360f8fc29. Thanks!
