### ISSUE TITLE
init OLED error

### ISSUE THREAD

**Issue by lionyhw** [Tinkertanker/pxt-oled-ssd1306#19]
https://makecode.microbit.org/_TWghaC5J6U1b

![microbit-screenshot (5)](https://user-images.githubusercontent.com/32665689/62355452-a2c79000-b541-11e9-8863-7438e3381bdd.png)

Only one line

**Comment by lionyhw** [comment]
error code is 844

**Comment by yjsoon** [comment]
Should be fixed in https://github.com/Tinkertanker/pxt-oled-ssd1306/commit/2de52e67fefa4ed13bb8ae2721ecec7763d872ac
