### ISSUE TITLE
how can i debug

### ISSUE THREAD

**Issue by hnwangkg-ezio** [Tinkertanker/pxt-oled-ssd1306#2]
Hello, I recently wanted to transplant my 1.8-inch LCD to micro:bit, but I have encountered some problems and I hope I can consult you. Can you teach me how you compile without BUG? Because of this I have no effective progress. Specifically this is:
I installed pxt under ubuntu, then programmed my c++ file, and also configured the .ts file, then I pushed them to github, and I downloaded it on makecod, and then when I dragged the blocks , there is a problem with the code. However, the browser did not give my specific and specific tips. I hope you can take your precious time and help me. The detailed code is on my github: https://github.com/hnwangkg-ezio/LCD1in8

**Comment by firemansamm** [comment]
I’ll take a look, closing as not a real issue with this project.
