### ISSUE TITLE
str.length() -> str.length

### ISSUE THREAD

**Issue by pelikhan** [Tinkertanker/pxt-oled-ssd1306#22]
length is property, drop the ``()``.
https://github.com/tinkertanker/pxt-oled-ssd1306/blob/0f127065d9a5dd24fd361f04cb496efb59117066/main.ts#L151

**Comment by yjsoon** [comment]
Got it, thanks!

**Comment by pelikhan** [comment]
Please create a new release so that the fix is picked up.

**Comment by yjsoon** [comment]
Done! Sorry, slipped my mind 😅
